[workspace]
name = "azure-ai-vision-sdk"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64"]

[dependencies]
nodejs = ">=20"
python = ">=3.11"
pip = "*"
playwright = ">=1.40"

[tasks]
npm-install = { cmd = "npm install", cwd = "samples/web/nextjs" }
dev = { cmd = "npm run dev", cwd = "samples/web/nextjs", depends-on = ["npm-install"] }
playwright-install = "playwright install"
test = { cmd = "playwright test", cwd = "samples/web/nextjs", depends-on = ["npm-install", "playwright-install"] }
blazor-npm-install = { cmd = "npm install", cwd = "samples/web/blazor/FaceLivenessDetectorSample.Client" }
blazor-build = { cmd = "dotnet build", cwd = "samples/web/blazor", depends-on = ["blazor-npm-install"] }
blazor-run = { cmd = "dotnet run --project FaceLivenessDetectorSample.Server", cwd = "samples/web/blazor", depends-on = ["blazor-npm-install"] }
blazor-test = { cmd = "dotnet test", cwd = "samples/web/blazor/tests/PlaywrightTests", depends-on = ["blazor-build", "playwright-install"] }
