# See GitHub actions documents:
# https://docs.github.com/en/actions/using-workflows
# https://github.com/actions/starter-workflows/tree/main/deployments

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.x' # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')
  VISION_KEY: ${{ secrets.VISION_KEY }}
  VISION_ENDPOINT: ${{ secrets.VISION_ENDPOINT }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
       os: [ubuntu-20.04, windows-latest]
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v3 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: 'Build .NET sample'
      shell: pwsh
      run: |
        pushd ./samples/csharp/image-analysis/dotnetcore
        dotnet build --configuration Release
        popd
    - name: 'Build .NET docs code snippets'
      shell: pwsh
      run: |
        pushd ./docs/learn.microsoft.com/csharp/image-analysis
        dotnet build --configuration Release
        popd
    - name: 'Run .NET docs code snippets'
      shell: pwsh
      run: |
        Write-Output "============== project 1 ==============" 
        pushd ./docs/learn.microsoft.com/csharp/image-analysis
        $output = dotnet run --project 1/1.csproj
        Write-Output $output
        if ($output -contains "Image height = 692") { exit 1 }
        Write-Output "============== project 2 =============="         
        $output = dotnet run --project 2/2.csproj
        Write-Output $output
        #dotnet run --project 3/3.csproj  # Skip, since required custom model
        Write-Output "========= project segmentation ========" 
        $output = dotnet run --project segmentation/segmentation.csproj
        Write-Output $output
        popd
 